concurrent = 1
check_interval = 0

[[runners]]
  name = "share_runner"
  url = "http://gitlab/"
  token = "your tocken"
  executor = "docker"
  clone_url = "http://gitlab"
  [runners.docker]
    image = "docker:stable"
    privileged = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
  [runners.cache]
    Insecure = false
